env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
  - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
  - import
rules:
  import/extensions:
    - error
    - ignorePackages
    - 
      js: never
      mjs: never
      jsx: never
      ts: never
      tsx: never
  import/order:
    - error
  no-shadow: off
  '@typescript-eslint/no-shadow':
    - error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error
    -
      vars: all
      args: after-used
      ignoreRestSiblings: true
  no-useless-constructor: off
  '@typescript-eslint/no-useless-constructor':
    - error
  no-empty-function: off
  '@typescript-eslint/no-empty-function': 
    - error
  no-extra-semi: off
  '@typescript-eslint/no-extra-semi':
    - error
  semi: off
  '@typescript-eslint/semi':
    - error
  no-underscore-dangle: off
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
