[googleCloud]
clientId = "client_id"
clientSecret = "client_secret"
refreshToken = "refresh_token"
projectId = "project_id"
# The format of dataset ID copied from Google Cloud UI is
# `{projectId}.{datasetId}`. Please fill in `{datasetId}` only.
datasetId = "dataset_id"
# The format of copied table ID is `{projectId}.{datasetId}.{tableId}`.
# Please fill in `{tableId}` only.
tableId = "table_id"
